cart/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('cart.views',
    (r'^$', 'show_cart', { 'template_name': 'cart/cart.html' }, 'show_cart'),
)

catalog/urls.py
from django.conf.urls.defaults import *
from django.views.generic.base import TemplateView

urlpatterns = patterns('catalog.views',
    (r'^$', 'index', { 'template_name':'catalog/index.html'}, 'catalog_home'),
    (r'^category/(?P<category_slug>[-\w]+)/$',
        'show_category', {
        'template_name':'catalog/category.html'},'catalog_category'),
    (r'^product/(?P<product_slug>[-\w]+)/$',
        'show_product', {
        'template_name':'catalog/product.html'},'catalog_product'),
    (r'^review/product/add/$', 'add_review'),
    (r'^tag/product/add/$', 'add_tag'),
    (r'^tag_cloud/$', 'tag_cloud', {'template_name': 'catalog/tag_cloud.html'}, 'tag_cloud'),
    (r'^tag/(?P<tag>[-\w]+)/$', 'tag', {'template_name': 'catalog/tag.html'}, 'tag'),

    (r'test/$', TemplateView.as_view(template_name='test.html')),
)

ecomstore/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from ecomstore import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ecomstore.views.home', name='home'),
    # url(r'^ecomstore/', include('ecomstore.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
    #other commented code here
    (r'^', include('catalog.urls')),
    (r'^cart/', include('cart.urls')),
    (r'^checkout/', include('checkout.urls')),
    (r'^accounts/', include('accounts.urls')),
    (r'^accounts/', include('django.contrib.auth.urls')),
    (r'^search/', include('search.urls')),
    (r'^robots.txt$', include('robots.urls')),
    (r'^', include('marketing.urls')),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            'show_indexes': True,
            }),
    )

handler404 = 'ecomstore.views.file_not_found_404'

catalog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save, post_delete
import tagging
from caching.caching import cache_update, cache_evict


class ActiveCategoryManger(models.Manager):
    def get_query_set(self):
        return super(ActiveCategoryManger, self).get_query_set().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True,
        help_text='Unique value for product page URL, created from name.')
    description = models.TextField()
    is_active = models.BooleanField(default=True)
    meta_keywords = models.CharField("Meta Keywords",max_length=255,
        help_text='Comma-delimited set of SEO keywords for meta tag')
    meta_description = models.CharField("Meta Description", max_length=255,
        help_text='Content for description meta tag')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    ojbects = models.Manager()
    active = ActiveCategoryManger()

    class Meta:
        db_table = 'categories'
        ordering = ['-created_at']
        verbose_name_plural = 'Categories'

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('catalog_category', (), { 'category_slug': self.slug })

    @property
    def cache_key(self):
        return self.get_absolute_url()


class ActiveProductManager(models.Manager):
    def get_query_set(self):
        return super(ActiveProductManager, self).get_query_set().filter(is_active=True)


class FeaturedProductManager(models.Manager):
    def all(self):
        return super(FeaturedProductManager, self).all()\
            .filter(is_active=True).filter(is_featured=True)


class Product(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True,
        help_text='Unique value for product page URL, created from name.')
    brand = models.CharField(max_length=50)
    sku = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=9,decimal_places=2)
    old_price = models.DecimalField(max_digits=9,decimal_places=2,
        blank=True,default=0.00)
    #image = models.CharField(max_length=50, null=True)
    image = models.ImageField(upload_to='images/products', null=True, blank=True)
    #thumbnail = models.ImageField(upload_to='images/products/thumbnails', null=True, blank=True)
    image_caption = models.CharField(max_length=200, null=True, blank=True)

    is_active = models.BooleanField(default=True)
    is_bestseller = models.BooleanField(default=False)
    is_featured = models.BooleanField(default=False)
    quantity = models.IntegerField()
    description = models.TextField()
    meta_keywords = models.CharField(max_length=255,
        help_text='Comma-delimited set of SEO keywords for meta tag')
    meta_description = models.CharField(max_length=255,
        help_text='Content for description meta tag')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField(Category)

    objects = models.Manager()
    active = ActiveProductManager()
    featured = FeaturedProductManager()

    class Meta:
        db_table = 'products'
        ordering = ['-created_at']

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return 'catalog_product', (), { 'product_slug': self.slug }

    @property
    def sale_price(self):
        if self.old_price > self.price:
            return self.price
        else:
            return None

    def cross_sells(self):
        from checkout.models import Order, OrderItem
        orders = Order.objects.filter(orderitem__product=self)
        order_items = OrderItem.objects.filter(order__in=orders).exclude(product=self)
        products = Product.active.filter(orderitem__in=order_items).distinct()
        return products

    def cross_sells_user(self):
        from checkout.models import Order, OrderItem
        from django.contrib.auth.models import User
        users = User.objects.filter(order__orderitem__product=self)
        items = OrderItem.objects.filter(order__user__in=users).exclude(product=self)
        products = Product.active.filter(orderitem__in=items).distinct()
        return products

    def cross_sells_hybrid(self):
        from checkout.models import Order, OrderItem
        from django.contrib.auth.models import User
        from django.db.models import Q
        orders = Order.objects.filter(orderitem__product=self)
        users = User.objects.filter(order__orderitem__product=self)
        items = OrderItem.objects.filter( Q(order__in=orders) |
                Q(order__user__in=users)
                ).exclude(product=self)
        products = Product.active.filter(orderitem__in=items).distinct()
        return products

    @property
    def cache_key(self):
        return self.get_absolute_url()

try:
    tagging.register(Product)
except tagging.AlreadyRegistered:
    pass

class ActiveProductReviewManager(models.Manager):
    def all(self):
        return super(ActiveProductReviewManager, self).all().filter(is_approved=True)

class ProductReview(models.Model):
    RATINGS = ((5,5),(4,4),(3,3),(2,2),(1,1),)
    product = models.ForeignKey(Product)
    user = models.ForeignKey(User)
    title = models.CharField(max_length=50)
    date = models.DateTimeField(auto_now_add=True)
    rating = models.PositiveSmallIntegerField(default=5, choices=RATINGS)
    is_approved = models.BooleanField(default=True)
    content = models.TextField()

    objects = models.Manager()
    approved = ActiveProductReviewManager()


post_save.connect(cache_update, sender=Product)
post_delete.connect(cache_evict, sender=Product)
post_save.connect(cache_update, sender=Category)
post_delete.connect(cache_evict, sender=Category)

catalog/views.py
# -*- coding: utf-8 -*-
import re
import string
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext
from django.core import urlresolvers
from django.http import HttpResponseRedirect, HttpResponse
from django.template.loader import render_to_string
from django.utils import simplejson
from django.core.serializers.json import DjangoJSONEncoder
import tagging
from tagging.models import Tag, TaggedItem
from catalog.models import Category, Product, ProductReview
from catalog.forms import ProductAddToCartForm, ProductReviewForm
from cart import cart
from ecomstore.settings import PRODUCTS_PER_ROW
from stats import stats

def index(request, template_name="catalog/index.html"):
    search_recs = stats.recommended_from_search(request)
    featured = Product.featured.all()[0:PRODUCTS_PER_ROW]
    recently_viewed = stats.get_recently_viewed(request)
    view_recs = stats.recommended_from_views(request)
    page_title = 'Musical Instruments and Sheet Music for Musicians'
    return render_to_response(template_name, locals(),
        context_instance=RequestContext(request))

def show_category(request, category_slug, template_name="catalog/category.html"):
    category_cache_key = request.path
    c = cache.get(category_cache_key)
    if not c:
        c = get_object_or_404(Category.active, slug=category_slug)
        cache.set(category_cache_key, c)
    products = c.product_set.filter(is_active=True)
    page_title = c.name
    meta_keywords = c.meta_keywords
    meta_description = c.meta_description
    return render_to_response(template_name, locals(),
        context_instance=RequestContext(request))

"""
# new product view, with POST vs GET detection
def show_product(request, product_slug, template_name="catalog/product.html"):
    p = get_object_or_404(Product, slug=product_slug)
    categories = p.categories.all()
    page_title = p.name
    meta_keywords = p.meta_keywords
    meta_description = p.meta_description
    product_reviews = ProductReview.approved.filter(product=p).order_by('-date')
    review_form = ProductReviewForm()
    # need to evaluate the HTTP method
    if request.method == 'POST':
        # add to cart... create the bound form
        postdata = request.POST.copy()
        form = ProductAddToCartForm(request, postdata)
        #check if posted data is valid
        if form.is_valid():
            #add to cart and redirect to cart page
            cart.add_to_cart(request)
            # if test cookie worked, get rid of it
            if request.session.test_cookie_worked():
                request.session.delete_test_cookie()
            url = urlresolvers.reverse('catalog_product', args=[product_slug])
            return HttpResponseRedirect(url)
    else:
        # it's a GET, create the unbound form. Note request as a kwarg
        form = ProductAddToCartForm(request=request, label_suffix=':')
    # assign the hidden input the product slug
    form.fields['product_slug'].widget.attrs['value'] = product_slug
    # set the test cookie on our first GET request
    request.session.set_test_cookie()
    stats.log_product_view(request, p) # add to product view
    return render_to_response("catalog/product.html", locals(),
        context_instance=RequestContext(request))
"""

# new product view, with POST vs GET detection
def show_product(request, product_slug, template_name="catalog/product.html"):
    product_cache_key = request.path
    # get product from cache
    p = cache.get(product_cache_key)
    # if a cache miss, fall back on database query
    if not p:
        p = get_object_or_404(Product.active, slug=product_slug)
        # store in cache for next time
        cache.set(product_cache_key, p)
    categories = p.categories.filter(is_active=True)
    page_title = p.name
    meta_keywords = p.meta_keywords
    meta_description = p.meta_description
    product_reviews = ProductReview.approved.filter(product=p).order_by('-date')
    review_form = ProductReviewForm()
    # need to evaluate the HTTP method
    if request.method == 'POST':
        # add to cart... create the bound form
        postdata = request.POST.copy()
        #form = ProductAddToCartForm(request, {"product_slug":product_slug, "quantity":quantity})
        form = ProductAddToCartForm(request, postdata)
        #check if posted data is valid
        if form.is_valid():
            #add to cart and redirect to cart page
            cart.add_to_cart(request)
            qty = cart.cart_distinct_item_count(request)
            subtotal = cart.cart_subtotal(request)
            response = simplejson.dumps({'success': 'True', 'qty':qty,
                'subtotal': subtotal}, cls=DjangoJSONEncoder)
            return HttpResponse(response,
                content_type="application/javascript; charset=utf-8")
        else:
            errors = form.errors
            response = simplejson.dumps({'success': 'False', 'errors': errors})
            return HttpResponse(response,
                content_type="application/javascript; charset=utf-8")
    else:
        # it's a GET, create the unbound form. Note request as a kwarg
        form = ProductAddToCartForm(request=request, label_suffix=':')
        # assign the hidden input the product slug
    form.fields['product_slug'].widget.attrs['value'] = product_slug
    # set the test cookie on our first GET request
    request.session.set_test_cookie()
    stats.log_product_view(request, p) # add to product view
    return render_to_response("catalog/product.html", locals(),
        context_instance=RequestContext(request))

@login_required
def add_review(request):
    form = ProductReviewForm(request.POST)
    if form.is_valid():
        review = form.save(commit=False)
        slug = request.POST.get('slug')
        product = Product.active.get(slug=slug)
        review.user = request.user
        review.product = product
        review.save()

        template = "catalog/product_review.html"
        html = render_to_string(template, {'review': review })
        response = simplejson.dumps({'success':'True', 'html': html})
    else:
        html = form.errors.as_ul()
        response = simplejson.dumps({'success':'False', 'html': html})
    return HttpResponse(response,
        content_type='application/javascript; charset=utf-8')

@login_required
def add_tag(request):
    tags = request.POST.get('tag','')
    slug = request.POST.get('slug','')
    if len(tags) > 2:
        p = Product.active.get(slug=slug)
        html = u''
        template = "catalog/tag_link.html"
        #for commatag in tags.split(','):
        for tag in re.split('[\s|\.|,]+', tags):
            if len(tag) > 2:
                tag = string.strip(re.sub(r'\W+', '-', tag, flags=re.U), '-')
                Tag.objects.add_tag(p,tag)
                #Tag.objects.add_tag(p, '"%s"' % tag)
        for tag in p.tags:
            html += render_to_string(template, {'tag': tag })
        response = simplejson.dumps({'success':'True', 'html': html })
    else:
        response = simplejson.dumps({'success':'False'})
    return HttpResponse(response,
        content_type='application/javascript; charset=utf8')

def tag_cloud(request, template_name="catalog/tag_cloud.html"):
    product_tags = Tag.objects.cloud_for_model(Product, steps=9,
        distribution=tagging.utils.LOGARITHMIC,
        filters={ 'is_active': True })
    page_title = 'Product Tag Cloud'
    return render_to_response(template_name, locals(),
        context_instance=RequestContext(request))

def tag(request, tag, template_name="catalog/tag.html"):
    products = TaggedItem.objects.get_by_model(Product.active, tag)
    return render_to_response(template_name, locals(),
        context_instance=RequestContext(request))

ecomstore/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext

def file_not_found_404(request):
    page_title = 'Page Not Found'
    return render_to_response('404.html', locals(),
        context_instance=RequestContext(request))

ecomstore/templates/catalog/category.html
{% extends "catalog.html" %}

{% block content %}
    <h1>{{ c.name }}</h1>
    {{ c.description }}
    <br /><br />
    {% for p in products %}
        {% include 'tags/product_thumbnail.html' %}
    {% endfor %}
{% endblock %}

ecomstore/templates/catalog/index.html
{% extends "catalog.html" %}
{% load catalog_tags %}

{%block content %}
    <h1>Welcome to Modern Musician!</h1>
    {% product_list recently_viewed 'Your Recently Viewed' %}
    {% product_list view_recs 'Similar Products' %}
    {% product_list featured 'Featured Products' %}
    {% product_list search_recs 'Recommended For You' %}
{% endblock %}

ecomstore/templates/catalog/product.html
{% extends "catalog.html" %}
{% load catalog_filters %}

{% block content %}
    <div id="product_image" >
        <img src="{{ p.image.url }}" alt="{{ p.name }}" />
        {{ p.image_caption }}
    </div>
    <h1>{{ p.name }}</h1>
    Brand: <em>{{ p.brand }}</em>
    <br /><br />
    SKU: {{ p.sku }}
    <br />
    In categor{{ categories.count|pluralize:"y,ies" }}:
    {% for c in categories %}
        <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        {% if not forloop.last %}, {% endif %}
    {% endfor %}
    <br /><br />
    {% if p.sale_price %}
        Was: <del>{{ p.old_price|currency }}</del>
        <br />
        Now: {{ p.price|currency }}
    {% else %}
        Price: {{ p.price|currency }}
    {% endif %}
    <br /><br />
    {% comment %}<form method="post" action="." class="cart">{% csrf_token %}
        {{ form.as_p }}
        <br />
        <input id="add_to_cart" type="submit" value="Add To Cart" name="submit" alt="Add To Cart" class="submit" />
        <div id="cart_errors"></div>
    </form>
    {% endcomment %}
    <div id="cart-form">
        <div id="cart-errors"></div>
        {{ form.as_p }}
        <br />
        <input id="add_to_cart" type="submit" value="Add To Cart" name="submit" alt="Add To Cart" class="submit" />
    </div>
    <div class="cb"><br /><br /></div>
    <h3>Related Products</h3>
    {% for p in p.cross_sells_hybrid %}
        {% include 'tags/product_thumbnail.html' %}
    {% empty %}
        No related products.
    {% endfor %}
    <div class="cb"><br /><br /></div>
    <h3>Product Description</h3>
    {{ p.description }}

    <div class="cb"><br /><br /></div>
    <h3>Product Tags</h3>
    <div id="tags">
        {% for tag in p.tags %}
            {% include 'catalog/tag_link.html' %}
        {% endfor %}
    </div>
    <br />
    {% if request.user.is_authenticated %}
        <label for="id_tag">Tag this product (must be at least three
            characters):</label>
        <br />
        <input id="id_tag" type="text" />
        <input type="submit" value=" Tag It " id="add_tag" />
    {% else %}
        <a href="{% url login %}?next={{ request.path }}">
            Log in to tag this product.
        </a>
    {% endif %}
    <div class="cb"><br /><br /></div>

    <div class="cb"><br /><br /></div>
    <h3>Product Reviews</h3>
    {% if request.user.is_authenticated %}
        <a id="add_review">Write a Review</a>
        <div id="review_form">
            <div id="review_errors"></div>
            <table>
                {{ review_form.as_table }}
                <tr><td colspan="2">
                    <input type="hidden" id="id_slug" value="{{ p.slug }}" />
                    <input type="submit" id="submit_review" value="Submit" />
                    <input type="submit" id="cancel_review" value="Cancel" />
                </td></tr>
            </table>
        </div>
    {% else %}
        <a href="{% url login %}?next={{ request.path }}">
            Log in to write your own review.
        </a>
    {% endif %}
    <div class="cb"></div>
    <div id="reviews">
        {% for review in product_reviews %}
            {% include 'catalog/product_review.html' %}
        {% empty %}
            <div id="no_reviews">
                No product reviews yet.
            </div>
        {% endfor %}
    </div>
    <div class="cb"><br /><br /></div>
{% endblock %}

ecomstore/templates/catalog/product_review.html
<div class="review">
    <div class="review-title">
        Rating: {{ review.rating }}
        <strong>{{ review.title }}</strong>
        by {{ review.user.username }}
    </div>
    {{ review.content|linebreaks }}
</div>

ecomstore/templates/catalog/tag.html
{% extends "catalog.html" %}
{% block content %}
    <h1>Products tagged with: '{{ tag }}'</h1>
    {% for p in products %}
        {% include 'tags/product_thumbnail.html' %}
    {% endfor %}
{% endblock %}

ecomstore/templates/catalog/tag_cloud.html
{% extends "catalog.html" %}

{% load tagging_tags %}

{% block content %}
    <h1>Product Tag Cloud</h1>
    {% for tag in product_tags %}
        <a href="/tag/{{ tag.name }}/" style="font-size:
                {{ tag.font_size|add:"11" }}px;">{{ tag.name }}</a>&nbsp;
    {% endfor %}
{% endblock %}

ecomstore/templates/catalog/tag_link.html
<a href="/tag/{{ tag.name }}/">{{ tag.name }}</a>&nbsp;