cart/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('cart.views',
    (r'^$', 'show_cart', { 'template_name': 'cart/cart.html' }, 'show_cart'),
)

ecomstore/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from ecomstore import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ecomstore.views.home', name='home'),
    # url(r'^ecomstore/', include('ecomstore.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
    #other commented code here
    (r'^', include('catalog.urls')),
    (r'^cart/', include('cart.urls')),
    (r'^checkout/', include('checkout.urls')),
    (r'^accounts/', include('accounts.urls')),
    (r'^accounts/', include('django.contrib.auth.urls')),
    (r'^search/', include('search.urls')),
    (r'^robots.txt$', include('robots.urls')),
    (r'^', include('marketing.urls')),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            'show_indexes': True,
            }),
    )

handler404 = 'ecomstore.views.file_not_found_404'

search/models.py
from django.db import models
from django.contrib.auth.models import User

class SearchTerm(models.Model):
    q = models.CharField(max_length=50)
    search_date = models.DateTimeField(auto_now_add=True)
    ip_address = models.IPAddressField()
    user = models.ForeignKey(User, null=True)
    tracking_id = models.CharField(max_length=50, default='')

    def __unicode__(self):
        return self.q

ecomstore/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext

def file_not_found_404(request):
    page_title = 'Page Not Found'
    return render_to_response('404.html', locals(),
        context_instance=RequestContext(request))

ecomstore/templates/tags/cart_box.html
{% load humanize catalog_filters %}

{% with cart_item_count as cart_count %}
    <a href="{% url show_cart %}">
        Shopping Cart
        <br />
        <span id="cart-items-count">{{ cart_count }}</span> Item{{ cart_count|pluralize }}<br />
        Subtotal: <span id="cart-subtotal">{{ cart_subtotal|currency }}</span>
    </a>
{% endwith %}

ecomstore/templates/tags/category_list.html
<h3>Categories</h3>
<ul id="categories">
{% with active_categories as cats %}
    {% for c in cats %}
    <li>
        {% ifequal c.get_absolute_url request_path %}
            {{ c.name }}<br />
        {% else %}
            <a href="{{ c.get_absolute_url }}" class="category">{{ c.name }}</a><br />
        {% endifequal %}
    </li>
    {% endfor %}
{% endwith %}
</ul>

ecomstore/templates/tags/footer.html
{% load cache %}

{% cache 3600 footer_links %}
<a href="{% url catalog_home %}">Home</a>
{% with flatpage_list as pages %}
    {% for page in pages %}
        <a href="{{ page.url }}">{{ page.title }}</a>
    {% endfor %}
{% endwith %}
<a href="{% url show_cart %}">Shopping Cart</a>
<a href="{% url tag_cloud %}">Tag Cloud</a>
{% endcache %}

ecomstore/templates/tags/form_table_row.html
<tr>
    <th>
        {% if form_field.field.required %}*{% endif %}
        {{ form_field.label_tag }}
    </th>
    <td>
        {% if form_field.errors %}
        <ul class="errorlist">
            {% for error in form_field.errors %}
            <li>{{ form_field.label }}: {{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {{ form_field }}
    </td>
</tr>

ecomstore/templates/tags/navigation.html
<ul>
    <li><a href="{% url catalog_home %}">Home</a></li>
    <li><a href="/about/">About</a></li>
    <li><a href="/privacy-policy/">Privacy</a></li>
    <li><a href="/contact/">Contact</a></li>
    <li>
        <a href="{% url my_account %}">My Account</a>
    </li>
</ul>
<div class="fr">
    <ul>
    {% if user.is_staff %}
        <li><a href="/admin">admin</a></li>
    {% endif %}
    {% if user.is_authenticated %}
        <li><a href="{% url django.contrib.auth.views.logout %}">Logout</a></li>
    {% else %}
        <li><a href="{% url register %}">Sign Up</a></li>
        <li><a href="{% url django.contrib.auth.views.login %}">Login</a></li>
    {% endif %}
    </ul>
</div>
<div class="cb"></div>

ecomstore/templates/tags/pagination_links.html
{% if p.has_other_pages %}
    {% if p.has_previous %}
        <a href="{{ request.path }}?{{ params }}&page={{ p.previous_page_number }}">
            &laquo; Previous
        </a>
    {% else %}
        &laquo; Previous
    {% endif %}
    | Page {{ p.number }} of {{ paginator.num_pages }} |
    {% if p.has_next %}
        <a href="{{ request.path }}?{{ params }}&page={{ p.next_page_number }}">
            Next &raquo;
        </a>
    {% else %}
        Next &raquo;
    {% endif %}
{% endif %}

ecomstore/templates/tags/product_list.html
{% for p in products %}
    {% if forloop.first %}
        <h3>{{ header_text }}</h3>
    {% endif %}
    {% include 'tags/product_thumbnail.html' %}
    {% if forloop.last %}
        <div class="cb">&nbsp;</div>
    {% endif %}
{% endfor %}

ecomstore/templates/tags/product_thumbnail.html
{% load thumbnail %}

<div class="product_thumbnail">
    <a href="{{ p.get_absolute_url }}">
        {% thumbnail p.image "100x100" as im %}
        <img src="{{ im.url }}" alt="{{ p.name }}" class="bn" />
        {% endthumbnail %}
        <br />
        {{ p.name }}
    </a>
</div>

ecomstore/templates/tags/search_box.html
<form id="search" action="{% url search_results %}" method="get">
    <h3><label for="id_q">Search</label></h3>
    <div style="text-align:right;">
        {{ form.q }}
        <input type="submit" value="Search" />
    </div>
</form>